FROM debian:jessie

MAINTAINER Thomas Kerpe <toke@toke.de>

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.docker.dockerfile="/Dockerfile" \
    org.label-schema.license="BSD 3-Clause" \
    org.label-schema.name="docker-mosquitto" \
    org.label-schema.url="https://hub.docker.com/r/toke/mosquitto/" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-type="Git" \
    org.label-schema.vcs-url="https://github.com/toke/docker-mosquitto"

RUN apt-get update && apt-get install -y wget && \
    wget -q -O - https://repo.mosquitto.org/debian/mosquitto-repo.gpg.key | gpg --import && \
    gpg -a --export 8277CCB49EC5B595F2D2C71361611AE430993623 | apt-key add - && \
    wget -q -O /etc/apt/sources.list.d/mosquitto-jessie.list https://repo.mosquitto.org/debian/mosquitto-jessie.list && \
    apt-get update && apt-get install -y mosquitto mosquitto-clients && \
    adduser --system --disabled-password --disabled-login mosquitto

RUN mkdir -p /mqtt/config /mqtt/data /mqtt/log
COPY config /mqtt/config/
RUN chown -R mosquitto:mosquitto /mqtt
VOLUME ["/mqtt/config", "/mqtt/data", "/mqtt/log"]

EXPOSE 1883 9001

ADD docker-entrypoint.sh /usr/bin/
#RUN curl https://raw.githubusercontent.com/pvgennip/sensor-data-portal/master/laradock/mosquitto/config/mosquitto.conf > /mqtt/config/mosquitto.conf
#RUN curl https://raw.githubusercontent.com/pvgennip/sensor-data-portal/master/laradock/mosquitto/config/conf.d/local_mosquitto.conf > /mqtt/config/conf.d/local_mosquitto.conf
#RUN curl https://raw.githubusercontent.com/pvgennip/sensor-data-portal/master/laradock/mosquitto/config/conf.d/mqtt_passwords > /mqtt/config/conf.d/mqtt_passwords
#ADD config/mosquitto.conf /mqtt/config/
#ADD config/conf.d/local_mosquitto.conf /mqtt/config/conf.d/
#ADD config/conf.d/mqtt_passwords /mqtt/config/conf.d/

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/usr/sbin/mosquitto", "-c", "/mqtt/config/mosquitto.conf"]